// Human-readable onboarding translations. Commands and diagnostic output keep stable English identifiers.
const rows = [
  ['en', 'English', 'User guide|Language|Add to group|Updates|Source code',
    '1. Add the bot to a supergroup as admin with Restrict Members.\n2. In the group, send /setup, then /doctor and /status, a few seconds apart.\n3. Review /incidents in observe mode; use /mode enforce when ready. /gate on enables new-member verification.\n4. If restricted, privately send /verify GROUP_ID using the ID in your challenge.\nVoice controls require a separate optional adapter. Raw UDP and account creation dates are unavailable.'],
  ['bn', 'বাংলা', 'ব্যবহারের গাইড|ভাষা|গ্রুপে যোগ করুন|আপডেট|সোর্স কোড',
    '১. Bot-কে supergroup-এ admin করে Restrict Members permission দিন।\n২. গ্রুপে /setup, তারপর কয়েক সেকেন্ড বিরতি দিয়ে /doctor ও /status দিন।\n৩. Observe mode-এ /incidents দেখুন; প্রস্তুত হলে /mode enforce দিন। নতুন সদস্যের verification চালু করতে /gate on দিন।\n৪. Restricted হলে challenge-এর group ID দিয়ে private chat-এ /verify GROUP_ID দিন।\nVoice controls-এর জন্য আলাদা optional adapter লাগে। Raw UDP ও account তৈরির তারিখ পাওয়া যায় না।'],
  ['zh', '中文', '使用指南|语言|添加到群组|更新|源代码',
    '1. 将机器人添加到超级群组，授予管理员和限制成员权限。\n2. 在群中依次发送 /setup、/doctor 和 /status，每次间隔几秒。\n3. 先在观察模式查看 /incidents；准备好后使用 /mode enforce。/gate on 启用新成员验证。\n4. 被限制时，在私聊中发送 /verify GROUP_ID，使用验证提示中的群组编号。\n语音控制需要单独的可选适配器。无法获取原始 UDP 或账号创建日期。'],
  ['hi', 'हिन्दी', 'उपयोग गाइड|भाषा|ग्रुप में जोड़ें|अपडेट|सोर्स कोड',
    '1. बॉट को supergroup में admin बनाएँ और Restrict Members अनुमति दें।\n2. ग्रुप में /setup, फिर कुछ सेकंड के अंतर पर /doctor और /status भेजें।\n3. Observe मोड में /incidents देखें; तैयार होने पर /mode enforce चलाएँ। /gate on नए सदस्यों का सत्यापन शुरू करता है।\n4. प्रतिबंधित होने पर निजी चैट में /verify GROUP_ID भेजें; challenge में दी गई ID इस्तेमाल करें।\nVoice नियंत्रण के लिए अलग वैकल्पिक adapter चाहिए। Raw UDP और खाता बनाने की तारीख उपलब्ध नहीं हैं।'],
  ['es', 'Español', 'Guía de uso|Idioma|Añadir al grupo|Novedades|Código fuente',
    '1. Añade el bot al supergrupo como administrador con permiso para restringir miembros.\n2. Envía /setup, /doctor y /status en el grupo, separados por unos segundos.\n3. Revisa /incidents en modo de observación; activa /mode enforce cuando estés listo. /gate on verifica a nuevos miembros.\n4. Si estás restringido, envía /verify GROUP_ID por privado con el ID del desafío.\nEl control de voz requiere un adaptador opcional separado. No se dispone de UDP bruto ni de fechas de creación de cuentas.'],
  ['ar', 'العربية', 'دليل الاستخدام|اللغة|إضافة إلى مجموعة|التحديثات|الكود المصدري',
    '1. أضف البوت إلى مجموعة فائقة كمشرف مع صلاحية تقييد الأعضاء.\n2. أرسل /setup ثم /doctor و /status في المجموعة مع فاصل بضع ثوانٍ.\n3. راجع /incidents في وضع المراقبة ثم فعّل /mode enforce عندما تكون جاهزًا. يفعّل /gate on تحقق الأعضاء الجدد.\n4. عند التقييد أرسل /verify GROUP_ID في الخاص باستخدام معرّف المجموعة في التحدي.\nيتطلب التحكم الصوتي محولًا اختياريًا منفصلًا. حزم UDP الخام وتواريخ إنشاء الحسابات غير متاحة.'],
  ['fr', 'Français', 'Guide utilisateur|Langue|Ajouter au groupe|Actualités|Code source',
    '1. Ajoutez le bot au supergroupe comme administrateur avec le droit de restreindre les membres.\n2. Envoyez /setup, /doctor puis /status dans le groupe, à quelques secondes d’intervalle.\n3. Consultez /incidents en observation ; activez /mode enforce quand vous êtes prêt. /gate on vérifie les nouveaux membres.\n4. Si vous êtes restreint, envoyez /verify GROUP_ID en privé avec l’identifiant du défi.\nLe contrôle vocal nécessite un adaptateur facultatif séparé. Le trafic UDP brut et les dates de création des comptes sont indisponibles.'],
  ['pt', 'Português', 'Guia de uso|Idioma|Adicionar ao grupo|Atualizações|Código-fonte',
    '1. Adicione o bot ao supergrupo como administrador com permissão para restringir membros.\n2. Envie /setup, /doctor e /status no grupo, com alguns segundos de intervalo.\n3. Revise /incidents no modo de observação; use /mode enforce quando estiver pronto. /gate on verifica novos membros.\n4. Se estiver restrito, envie /verify GROUP_ID no privado com o ID do desafio.\nO controle de voz exige um adaptador opcional separado. UDP bruto e datas de criação de contas não estão disponíveis.'],
  ['id', 'Bahasa Indonesia', 'Panduan pengguna|Bahasa|Tambahkan ke grup|Pembaruan|Kode sumber',
    '1. Tambahkan bot ke supergrup sebagai admin dengan izin membatasi anggota.\n2. Kirim /setup, /doctor, lalu /status di grup, dengan jeda beberapa detik.\n3. Tinjau /incidents dalam mode observasi; gunakan /mode enforce saat siap. /gate on memverifikasi anggota baru.\n4. Jika dibatasi, kirim /verify GROUP_ID melalui chat pribadi menggunakan ID dari tantangan.\nKontrol suara memerlukan adaptor opsional terpisah. UDP mentah dan tanggal pembuatan akun tidak tersedia.'],
  ['ur', 'اردو', 'استعمال کی رہنمائی|زبان|گروپ میں شامل کریں|اپ ڈیٹس|سورس کوڈ',
    '1. بوٹ کو supergroup میں admin بنائیں اور Restrict Members کی اجازت دیں۔\n2. گروپ میں /setup، پھر چند سیکنڈ کے وقفے سے /doctor اور /status بھیجیں۔\n3. Observe موڈ میں /incidents دیکھیں؛ تیار ہونے پر /mode enforce چلائیں۔ /gate on نئے ارکان کی تصدیق فعال کرتا ہے۔\n4. پابندی کی صورت میں نجی چیٹ میں /verify GROUP_ID بھیجیں، challenge والی ID استعمال کریں۔\nصوتی کنٹرول کے لیے الگ اختیاری adapter چاہیے۔ Raw UDP اور اکاؤنٹ بنانے کی تاریخ دستیاب نہیں۔'],
  ['ru', 'Русский', 'Инструкция|Язык|Добавить в группу|Обновления|Исходный код',
    '1. Добавьте бота в супергруппу как администратора с правом ограничивать участников.\n2. Отправьте в группе /setup, /doctor и /status с интервалом в несколько секунд.\n3. Просмотрите /incidents в режиме наблюдения; затем включите /mode enforce. /gate on включает проверку новых участников.\n4. При ограничении отправьте боту лично /verify GROUP_ID с ID из задания.\nДля управления голосовыми чатами нужен отдельный дополнительный адаптер. Сырые UDP-пакеты и даты создания аккаунтов недоступны.'],
  ['ko', '한국어', '사용 가이드|언어|그룹에 추가|업데이트|소스 코드',
    '1. 봇을 슈퍼그룹에 관리자로 추가하고 멤버 제한 권한을 부여하세요.\n2. 그룹에서 /setup, /doctor, /status를 몇 초 간격으로 보내세요.\n3. 관찰 모드에서 /incidents를 검토한 후 /mode enforce를 실행하세요. /gate on은 새 멤버 인증을 켭니다.\n4. 제한된 경우 인증 안내의 그룹 ID로 비공개 채팅에서 /verify GROUP_ID를 보내세요.\n음성 제어에는 별도의 선택적 어댑터가 필요합니다. 원시 UDP 패킷과 계정 생성일은 확인할 수 없습니다.'],
  ['ja', '日本語', '使い方|言語|グループに追加|更新情報|ソースコード',
    '1. ボットをスーパーグループの管理者にし、メンバー制限の権限を与えてください。\n2. グループで /setup、/doctor、/status を数秒ずつ間隔を空けて送信します。\n3. 監視モードで /incidents を確認し、準備ができたら /mode enforce を使います。/gate on で新規メンバーの確認を有効にします。\n4. 制限された場合は、確認メッセージのグループ ID を使い、個別チャットで /verify GROUP_ID を送ります。\n音声制御には別途オプションのアダプターが必要です。生の UDP パケットやアカウント作成日は取得できません。'],
  ['de', 'Deutsch', 'Anleitung|Sprache|Zur Gruppe hinzufügen|Neuigkeiten|Quellcode',
    '1. Füge den Bot als Administrator mit dem Recht zum Einschränken von Mitgliedern zur Supergruppe hinzu.\n2. Sende /setup, /doctor und /status in der Gruppe mit einigen Sekunden Abstand.\n3. Prüfe /incidents im Beobachtungsmodus; aktiviere danach /mode enforce. /gate on prüft neue Mitglieder.\n4. Sende bei einer Einschränkung privat /verify GROUP_ID mit der ID aus der Aufgabe.\nSprachsteuerung benötigt einen separaten optionalen Adapter. Rohe UDP-Pakete und Kontoerstellungsdaten sind nicht verfügbar.'],
  ['tr', 'Türkçe', 'Kullanım kılavuzu|Dil|Gruba ekle|Güncellemeler|Kaynak kodu',
    '1. Botu süpergruba üye kısıtlama yetkisi olan yönetici olarak ekleyin.\n2. Grupta birkaç saniye arayla /setup, /doctor ve /status gönderin.\n3. Gözlem modunda /incidents kayıtlarını inceleyin; hazır olduğunuzda /mode enforce kullanın. /gate on yeni üyeleri doğrular.\n4. Kısıtlanırsanız görevdeki grup kimliğiyle özel sohbette /verify GROUP_ID gönderin.\nSes kontrolü ayrı bir isteğe bağlı adaptör gerektirir. Ham UDP ve hesap oluşturma tarihleri kullanılamaz.'],
  ['it', 'Italiano', 'Guida all’uso|Lingua|Aggiungi al gruppo|Aggiornamenti|Codice sorgente',
    '1. Aggiungi il bot al supergruppo come amministratore con il permesso di limitare i membri.\n2. Invia /setup, /doctor e /status nel gruppo, a qualche secondo di distanza.\n3. Controlla /incidents in modalità osservazione; poi attiva /mode enforce. /gate on verifica i nuovi membri.\n4. Se sei limitato, invia in privato /verify GROUP_ID con l’ID indicato nella verifica.\nIl controllo vocale richiede un adattatore opzionale separato. UDP grezzo e date di creazione degli account non sono disponibili.'],
  ['fa', 'فارسی', 'راهنمای استفاده|زبان|افزودن به گروه|تازه‌ها|کد منبع',
    '1. ربات را با دسترسی محدود کردن اعضا، مدیر سوپرگروه کنید.\n2. در گروه /setup، سپس /doctor و /status را با چند ثانیه فاصله بفرستید.\n3. در حالت مشاهده /incidents را بررسی کنید؛ سپس /mode enforce را فعال کنید. /gate on تأیید اعضای جدید را روشن می‌کند.\n4. هنگام محدودیت، با شناسه گروه در پیام تأیید، /verify GROUP_ID را در خصوصی بفرستید.\nکنترل صوتی به آداپتور اختیاری جداگانه نیاز دارد. UDP خام و تاریخ ایجاد حساب در دسترس نیست.'],
  ['vi', 'Tiếng Việt', 'Hướng dẫn sử dụng|Ngôn ngữ|Thêm vào nhóm|Cập nhật|Mã nguồn',
    '1. Thêm bot vào siêu nhóm làm quản trị viên có quyền hạn chế thành viên.\n2. Gửi /setup, /doctor và /status trong nhóm, cách nhau vài giây.\n3. Xem /incidents ở chế độ quan sát; dùng /mode enforce khi sẵn sàng. /gate on bật xác minh thành viên mới.\n4. Nếu bị hạn chế, gửi riêng /verify GROUP_ID bằng ID nhóm trong thử thách.\nĐiều khiển thoại cần bộ điều hợp tùy chọn riêng. Không có dữ liệu UDP thô hay ngày tạo tài khoản.'],
  ['ta', 'தமிழ்', 'பயனர் வழிகாட்டி|மொழி|குழுவில் சேர்க்கவும்|புதுப்பிப்புகள்|மூலக் குறியீடு',
    '1. உறுப்பினர்களைக் கட்டுப்படுத்தும் அனுமதியுடன் bot-ஐ supergroup நிர்வாகியாகச் சேர்க்கவும்.\n2. குழுவில் /setup, பின்னர் சில வினாடிகள் இடைவெளியில் /doctor மற்றும் /status அனுப்பவும்.\n3. கண்காணிப்பு முறையில் /incidents பார்க்கவும்; தயாரானதும் /mode enforce பயன்படுத்தவும். /gate on புதிய உறுப்பினர்களைச் சரிபார்க்கும்.\n4. கட்டுப்படுத்தப்பட்டால், சரிபார்ப்பில் உள்ள குழு ID-யுடன் தனிப்பட்ட உரையாடலில் /verify GROUP_ID அனுப்பவும்.\nகுரல் கட்டுப்பாட்டிற்கு தனி விருப்ப adapter தேவை. Raw UDP மற்றும் கணக்கு உருவாக்கிய தேதி கிடைக்காது.'],
  ['te', 'తెలుగు', 'వినియోగ మార్గదర్శి|భాష|గ్రూప్‌కు జోడించండి|నవీకరణలు|సోర్స్ కోడ్',
    '1. సభ్యులను పరిమితం చేసే అనుమతితో bot‌ను supergroup అడ్మిన్‌గా జోడించండి.\n2. గ్రూప్‌లో /setup, తరువాత కొన్ని సెకన్ల విరామంతో /doctor మరియు /status పంపండి.\n3. పరిశీలన మోడ్‌లో /incidents చూడండి; సిద్ధమైనప్పుడు /mode enforce వాడండి. /gate on కొత్త సభ్యుల ధృవీకరణను ప్రారంభిస్తుంది.\n4. పరిమితి ఉంటే, ధృవీకరణలోని గ్రూప్ IDతో ప్రైవేట్ చాట్‌లో /verify GROUP_ID పంపండి.\nవాయిస్ నియంత్రణకు ప్రత్యేక ఐచ్ఛిక adapter అవసరం. Raw UDP, ఖాతా సృష్టించిన తేదీ అందుబాటులో ఉండవు.']
];

export const LANGUAGES = Object.freeze(Object.fromEntries(rows.map(([code, name, labels, guide]) => {
  const [help, language, add, updates, source] = labels.split('|');
  return [code, Object.freeze({ code, name, help, language, add, updates, source, guide })];
})));
export function languageCode(value) {
  const code = String(value || '').toLowerCase().split(/[-_]/)[0];
  return Object.hasOwn(LANGUAGES, code) ? code : 'en';
}
export function languageKeyboard() {
  const buttons = Object.values(LANGUAGES).map(({ code, name }) => ({ text: name, callback_data: `ui:lang:${code}` }));
  return { inline_keyboard: Array.from({ length: Math.ceil(buttons.length / 2) }, (_, i) => buttons.slice(i * 2, i * 2 + 2)) };
}
